### PR TITLE
Fixed bug in FodselsnummerValidator.getManyFodselsnummerForDate

### PR DESCRIPTION
**Pull request by ndyb**
Tried to generate all Fodselsnummer for a given date, and realized that the amount generated was way too low. This also affects the randomness og the random Fodselsnummer generator (getFodselsnummerForDate) as it uses the same function to generate all Fodselsnummer.

I need this for a project, but don't really want to vendor the code. A quick merge of the fix would be appreciated, if possible.

### CODE REVIEW

**Comment by judoole** [comment]
Sorry for the late reply @ndyb! I wasn't even watching this repo :anguished: 
Weird that travis didn't pick up the pull request also. 

I'm not too familiar with the code in question and the getMod11Weights in FodselsnummerValidator.java. Maybe @perkrimen has some say? 

Tests runs all okey on my machine, so I say accept and build new release.
cc @steinim @landro

**Comment by landro** [comment]
@judoole Could you please build a new release? This is a serious bug, and should bed shipped immediately.

**Comment by judoole** [comment]
:+1:

**Comment by judoole** [comment]
Crap. I've got a new machine and haven't set up gpg keys and what not. Ages since I did a release like this. Are you able to release in a jiffy @steinim ?

**Comment by steinim** [comment]
I´ll try :)


2015-04-20 14:12 GMT+02:00 Ole Christian Langfjæran <
notifications@github.com>:

> Crap. I've got a new machine and haven't set up gpg keys and what not.
> Ages since I did a release like this. Are you able to release in a jiffy
> @steinim <https://github.com/steinim> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bekkopen/NoCommons/pull/20#issuecomment-94435977>.
>



-- 
- Stein Inge

**Comment by steinim** [comment]
It's released @judoole @ndyb @landro :)

**Comment by ndyb** [comment]
Awesome, thanks! :)

**Pull request merged**
